### server port
server:
  port: 8082

#Keycloak Configuration
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: angular
  resource: springboot-test
  bearer-only: true
  ssl-required: external
